stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm ci && npm test
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-hellonode:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34243
- name: Fire up!
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
