stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm ci && npm test
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/app:v1
      registry: 127.0.0.1:34740
- name: Fire up!
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
