apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: test-node
        image: test/app:v1
        ports:
        - containerPort: 8080
