apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        image: test/app:v1
        ports:
        - containerPort: 8080
