apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        image: deployment.apps/test-node-deployment
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
