kind: Service
apiVersion: v1
metadata:
  name: hellonode-service
spec:
  selector:
    app: hellonode
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-hellonode
  labels:
    app: hellonode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: hellonode
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3000
